# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/koenigr/git/stm32f407-register-level-access-control

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/koenigr/git/stm32f407-register-level-access-control

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/koenigr/git/stm32f407-register-level-access-control/CMakeFiles /home/koenigr/git/stm32f407-register-level-access-control//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/koenigr/git/stm32f407-register-level-access-control/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stm32f407_access_control

# Build rule for target.
stm32f407_access_control: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stm32f407_access_control
.PHONY : stm32f407_access_control

# fast build rule for target.
stm32f407_access_control/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32f407_access_control.dir/build.make CMakeFiles/stm32f407_access_control.dir/build
.PHONY : stm32f407_access_control/fast

Core/main.o: Core/main.c.o
.PHONY : Core/main.o

# target to build an object file
Core/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32f407_access_control.dir/build.make CMakeFiles/stm32f407_access_control.dir/Core/main.c.o
.PHONY : Core/main.c.o

Core/main.i: Core/main.c.i
.PHONY : Core/main.i

# target to preprocess a source file
Core/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32f407_access_control.dir/build.make CMakeFiles/stm32f407_access_control.dir/Core/main.c.i
.PHONY : Core/main.c.i

Core/main.s: Core/main.c.s
.PHONY : Core/main.s

# target to generate assembly for a file
Core/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32f407_access_control.dir/build.make CMakeFiles/stm32f407_access_control.dir/Core/main.c.s
.PHONY : Core/main.c.s

Startup/startup_stm32f407xx.o: Startup/startup_stm32f407xx.s.o
.PHONY : Startup/startup_stm32f407xx.o

# target to build an object file
Startup/startup_stm32f407xx.s.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32f407_access_control.dir/build.make CMakeFiles/stm32f407_access_control.dir/Startup/startup_stm32f407xx.s.o
.PHONY : Startup/startup_stm32f407xx.s.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stm32f407_access_control"
	@echo "... Core/main.o"
	@echo "... Core/main.i"
	@echo "... Core/main.s"
	@echo "... Startup/startup_stm32f407xx.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

